## Fake UCI Heart Disease Generator¶
### Description
* Number of Instances: 30000
* Dataset Characterstics:
* Associated Tasks: Calssification Problem
* Number of Attributes: 14
### Meaning of column headings
* Age is the age of candidate.
* Sex has numeric values. 1 denotes male and 0 denotes female.
* Chest Pain pain has values between 0-3. The types of angina that are described in the research paper. The higher the number, the lesser are the odds of heart attack.
* Resting blood pressure is normal pressure with no exercise.
* Cholesterol means the blockage for blood supply in the blood vessels.
* Fasting Blood Pressure is blood sugar taken after a long gap between a meal and the test. Typically, it's taken before any meal in the morning.
* Rest ECG results means ECG values taken while person is on rest which means no exercise and normal functioning of heart is happening.
* The Maximum Heart Rate achieved. Exercise induced angina is chest pain while exercising or doing any physical activity. 
* ST Depression is the difference between value of ECG at rest and after exercise.
* ST Slope is the tangent to the depression value. 
* The number of major blood vessels supplying blood to heart blocked. The Types of thalassemia.ca
* Target:Heart attack prediction where 1 denotes Heart attack occured and 0 where it din't take occur.
### Source
#### Creator:

Tamir Suliman tsulima2@gmu.edu

### Information
This database contains the following attributes:

1. id: patient identification number
2. age: age in years
3. sex: sex (1 = male; 0 = female)
4. cp: chest pain type
    
### Code


In [20]:
# Import libraries 
import random
import numpy as np
import pandas as pd
# Number of Patients
N = 30000 # Number of Records
id = np.arange( 0, N )
np.random.seed(2021)
# General Attributes 
age = np.random.randint(21,77,size=N) # Age
sex = np.random.randint(2, size=N) # Sex Male = 1 , Female = 0
print(sex)
print(age)
# Chest Pain
# chest pain type 
# angina – chest pain caused by restricted blood flow to the heart muscle
# -- Value 1: typical angina
# -- Value 2: atypical angina
# -- Value 3: non-anginal pain
# -- Value 4: asymptomatic
chest_pain = np.random.randint(1,5, size=N) 
print(chest_pain)
# trestbps
trestbps = np.random.randint(120,220, size=N)
print(trestbps)
# chol
chol = np.random.randint(126,564, size=N)
print(chol)
#fbs
fbs = np.random.randint(2, size=N)
print(fbs)
# restecg 
restecg = np.random.randint(0,3, size=N)
print(restecg)
# thalach
thalach = np.random.randint(71,202, size=N)
print(thalach)
# exang
exang = np.random.randint(2, size=N)
print(exang)
#oldpeak
oldpeak = np.random.randint(0.0,6.2, size=N)
print(oldpeak)
# slope
slope = np.random.randint(0,3, size=N)
print(slope)
# ca
ca =  np.random.randint(0,5, size=N)
print(ca)
#thal
thal = np.random.randint(0,4, size=N) 
print(thal)
# target
target = np.random.randint(2, size=N)
print(target)

# Join all  data
df = pd.DataFrame({'id':id, 'age':age, 'sex':sex,'cp':chest_pain,'chol':chol,'fbs':fbs,'thalach':thalach,'exang':exang,'oldpeak':oldpeak,'slope':slope,'ca':ca,'thal':thal,'target':target});

# Export generated data to CSV dataset file
df.to_csv(r'UCI_Heart_Dataset_Test_Fake_export.csv', index = False, header = True)
# Print the data 
df.head(10000)

[0 0 1 ... 1 0 0]
[73 42 21 ... 67 26 28]
[1 1 4 ... 1 4 2]
[201 213 137 ... 156 133 124]
[342 224 447 ... 295 221 414]
[1 0 1 ... 1 1 1]
[2 1 0 ... 2 0 2]
[181 197 109 ...  78  89 119]
[1 1 1 ... 0 0 1]
[5 4 0 ... 5 0 5]
[0 2 0 ... 2 0 2]
[0 1 1 ... 0 4 4]
[2 1 1 ... 3 3 0]
[0 0 1 ... 1 1 1]


id  age  sex  cp  chol  fbs  thalach  exang  oldpeak  slope  ca  thal  \
0        0   73    0   1   342    1      181      1        5      0   0     2   
1        1   42    0   1   224    0      197      1        4      2   1     1   
2        2   21    1   4   447    1      109      1        0      0   1     1   
3        3   66    1   3   420    0      125      0        0      2   3     1   
4        4   51    0   4   355    0       83      0        4      1   3     1   
...    ...  ...  ...  ..   ...  ...      ...    ...      ...    ...  ..   ...   
9995  9995   37    0   4   393    0      127      0        2      2   0     0   
9996  9996   30    0   2   161    0       92      1        0      2   3     0   
9997  9997   32    1   2   425    0       83      0        3      1   4     0   
9998  9998   59    0   4   500    0      144      0        4      2   4     2   
9999  9999   53    1   1   286    0      156      1        4      1   1     1   

      target  
0          0  
1          0  
2          1  
3          1  
4          0  
...      ...  
9995       0  
9996       0  
9997       0  
9998       1  
9999       1  

[10000 rows x 13 columns]